export default {
  // Member
  SPLASH: 'Splash',
  OPTIONS_AUTENTIKASI: 'OptionsAutentikasi',
  MAIN_APP: 'MainApp',
  LOGIN: 'Login',
  DAFTAR_AKUN_KONSUMEN: 'DaftarAkunKonsumen',
  DASHBOARD_MEMBER: 'Beranda',
  TRANSAKSI_MEMBER: 'Transaksi',
  PROFILE_MEMBER: 'ProfileMember',
  CHAT_DOKTER: 'ChatDokter',
  DETAIL_CHAT: 'DetailChat',
  EDIT_PROFILE: 'EditProfile',
  CHATING: 'Chating',
  DETAIL_ARTIKEL: 'DetailArtikel',
  KONSULTASI: 'Konsultasi',
  BUAT_JANJI: 'BuatJanji',
  DETAIL_BUAT_JANJI: 'DetailBuatJanji',
  INFORMASI_BUAT_JANJI: 'InformasiBuatJanji',
  TOKO_KESEHATAN_PRODUK: 'TokoKesehatanProduk',
  SPESIALIS_DOKTER: 'SpesialisDokter',
  SPESIALIS_BUAT_JANJI: "SpesialisBuatJanji",
  DETAIL_PRAKTEK: "DetailPraktek",
  LANJUTKAN_PEMBAYARAN: 'LanjutkanPembayaran',
  DETAIL_PRODUK: 'DetailProduk',
  KERANJANG: 'Keranjang',
  UPDATE_PASSWORD_MEMBER: 'UpdatePasswordMember',
  ALAMAT_TERSIMPAN: 'AlamatTersimpan',
  KEAHLIAN_DOKTER: 'KeahlianDokter',
  RINGKASAN_PEMBAYARAN: 'RingkasanPembayaran',
  All_DATA_RS: 'AllDataRs',
  All_DATA_PRODUK: 'AllDataProduk',
  RINGKASAN_PEMBAYARAN_PRODUK: "RingkasanPembayaranProduk",
  LoadingScreen: "LoadingScreen",
  ALL_ARTIKEL: "AllArtikel",
  CHAT_PUSHER: "ChatPusher",
  DATA_ALAMAT: "DataAlamat",
  CHAT_PERAWAT: "ChatPerawat",
  PRODUK_BY_KATEGORI: "ProdukByKategori",
  PEMBAYARAN_PRODUK: "Pembayaran",
  DETAIL_TRANSAKSI_BUAT_JANJI: "DetailTransaksiBuatJanji",
  ALL_ANTRIAN: "AllAntrian",
  OBAT_RESEP: "ObatResep",
  DETAIL_OBAT_RESEP: "DetailObatResep",
  INVOICE: "Invoice",
  CHATBOT:"ChatBot",
  DIAGNOSA:"Diagnosa",
  JADWAL_DOKTER: "JadwalDokter",
  JADWAL_POLIKLINIK: "JadwalPoliklinik",


  // Dokter
  DASHBOARD_DOKTER: 'DashboardDokter',
  MAIN_DOKTER: 'MainDokter',
  PRODUK_DOKTER: "ProdukDokter",
  CHATING_DOKTER: 'ChatingDokter',
  KONSULTASI_DOKTER: "KonsultasiDokter",
  DETAIL_KONSULTASI: "DetailKonsultasi",
  PROFILE_DOKTER: "ProfileAkunDokter",
  EDIT_PROFILE_DOKTER: "EditProfileDokter",
  ALL_DATA_RUMAH_SAKIT_TERDEKAT: "AllDataRumahSakitTerdekat",
  ALL_DATA_APOTEK_TERDEKAT: "AllDataApotekTerdekat",
  PUSHER: "Pusher",
  RESERVASI: "Reservasi",
  TRANSAKSI_DOKTER: "TransaksiDokter",
  TAMBAH_REKOMENDASI: "TambahRekomendasi",
  JADWAL_BUAT_JANJI: "JadwalBuatJanji",
  DETAIL_JADWAL_JANJI: "DetailJadwalJanji",
  LANJUTKAN_PEMBAYARAN_KONSULTASI: "LanjutkanPembayaranKonsultasi",
  RESEP_OBAT: "ResepObat",
  KERANJANG_RESEP: "KeranjangResep",
  LIST_RESEP_OBAT: "ListResepObat",
  DETAIL_LIST_RESEP_OBAT: "DetailListResepObat",

  // Perawat
  DASHBOARD_PERAWAT: "DashboardPerawat",
  MAIN_PERAWAT: "MainPerawat",
  PROFILE_PERAWAT: "ProfilePerawat",
  RIWAYAT_TRANSAKSI_PERAWAT: "RiwayatTransaksiPerawat",
  KONSULTASI_PERAWAT: "KonsultasiPerawat",
  DETAIL_KONSULTASI_PERAWAT: "DetailKonsultasiPerawat",
  LANJUTKAN_PERAWATAN: "LanjutkanPerawatan",
  TRANSAKSI_RAWAT_JALAN: "TransaksiRawatJalan",

  // PUBLIC
  LUPA_PASSWORD_AUTENTIKASI: "LupaPasswordAutentikasi"
};
